let $list := <list>
  <item>https://wellcomeopenresearch.org/articles/1-1/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-1/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-10/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-10/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-11/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-12/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-13/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-14/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-15/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-16/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-16/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-17/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-18/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-18/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-19/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-19/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-19/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-2/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-2/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-20/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-21/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-22/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-22/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-23/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-23/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-24/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-25/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-25/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-26/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-27/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-27/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-28/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-28/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-29/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-3/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-3/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-30/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-30/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-31/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-32/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-32/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-32/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-33/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-4/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-5/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-6/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-6/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-7/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-7/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-8/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/1-9/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-1/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-10/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-10/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-100/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-100/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-101/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-102/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-103/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-104/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-105/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-105/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-105/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-106/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-107/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-107/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-108/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-109/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-109/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-11/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-110/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-110/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-111/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-112/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-113/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-114/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-114/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-114/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-115/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-115/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-116/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-116/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-117/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-117/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-117/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-118/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-118/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-119/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-119/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-12/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-120/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-120/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-120/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-121/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-121/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-121/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-13/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-13/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-14/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-15/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-16/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-16/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-17/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-17/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-18/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-19/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-2/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-2/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-20/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-20/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-21/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-21/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-22/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-22/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-22/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-22/v4/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-23/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-23/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-23/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-24/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-25/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-25/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-26/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-27/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-28/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-28/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-28/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-29/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-29/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-3/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-3/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-30/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-31/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-31/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-32/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-32/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-33/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-34/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-34/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-35/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-36/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-36/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-37/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-37/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-38/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-39/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-39/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-4/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-4/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-40/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-40/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-41/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-41/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-42/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-43/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-43/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-44/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-44/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-45/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-45/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-46/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-47/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-47/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-48/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-48/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-49/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-5/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-50/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-50/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-51/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-52/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-52/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-53/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-53/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-54/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-55/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-55/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-56/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-57/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-58/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-59/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-6/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-6/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-60/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-60/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-61/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-62/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-63/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-64/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-64/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-65/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-66/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-66/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-66/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-67/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-68/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-69/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-69/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-7/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-70/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-71/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-72/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-72/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-73/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-73/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-74/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-75/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-76/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-76/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-77/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-77/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-78/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-78/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-79/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-8/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-80/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-80/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-81/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-82/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-83/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-83/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-84/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-84/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-85/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-86/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-87/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-87/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-88/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-89/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-89/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-9/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-90/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-91/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-92/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-93/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-93/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-93/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-94/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-95/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-95/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-96/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-97/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-97/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-98/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-98/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/2-99/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-1/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-10/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-10/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-100/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-101/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-102/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-103/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-103/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-104/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-104/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-105/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-105/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-106/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-107/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-108/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-108/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-109/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-109/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-109/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-109/v4/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-11/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-11/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-110/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-110/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-111/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-111/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-112/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-113/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-113/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-114/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-114/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-115/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-115/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-116/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-116/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-117/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-118/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-118/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-119/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-12/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-120/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-120/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-121/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-122/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-123/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-124/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-125/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-126/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-127/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-128/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-128/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-129/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-13/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-13/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-130/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-130/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-131/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-132/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-132/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-133/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-134/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-134/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-135/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-135/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-136/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-137/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-137/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-138/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-139/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-139/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-139/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-14/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-14/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-140/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-140/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-141/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-141/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-142/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-142/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-143/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-143/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-144/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-145/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-146/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-147/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-148/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-149/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-149/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-149/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-15/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-15/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-150/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-150/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-151/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-151/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-152/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-153/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-154/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-155/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-156/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-156/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-157/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-157/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-157/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-158/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-159/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-159/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-16/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-160/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-161/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-162/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-163/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-163/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-164/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-165/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-166/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-17/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-18/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-18/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-19/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-19/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-2/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-2/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-20/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-21/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-21/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-22/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-23/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-24/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-25/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-26/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-27/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-27/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-27/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-28/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-29/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-29/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-3/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-30/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-31/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-31/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-32/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-33/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-33/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-34/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-34/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-35/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-36/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-37/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-38/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-38/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-39/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-39/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-4/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-4/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-4/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-40/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-41/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-42/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-43/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-44/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-44/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-45/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-46/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-47/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-47/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-48/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-49/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-49/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-5/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-5/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-50/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-51/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-52/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-53/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-53/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-54/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-55/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-55/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-56/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-57/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-58/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-58/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-59/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-59/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-6/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-6/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-60/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-61/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-61/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-61/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-62/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-63/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-63/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-64/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-64/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-65/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-65/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-66/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-67/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-67/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-67/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-68/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-69/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-7/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-70/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-70/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-70/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-70/v4/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-71/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-72/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-72/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-73/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-74/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-75/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-76/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-76/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-77/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-78/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-79/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-79/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-79/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-8/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-80/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-80/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-81/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-81/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-82/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-82/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-82/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-83/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-84/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-84/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-85/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-85/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-86/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-86/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-87/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-87/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-88/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-89/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-9/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-9/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-90/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-90/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-91/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-92/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-93/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-94/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-95/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-96/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-96/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-97/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-98/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-98/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-99/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/3-99/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-1/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-1/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-10/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-100/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-100/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-101/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-102/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-103/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-104/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-105/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-106/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-107/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-108/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-109/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-11/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-11/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-110/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-111/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-112/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-113/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-114/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-115/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-116/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-117/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-118/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-119/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-12/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-12/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-120/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-121/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-122/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-123/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-124/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-125/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-126/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-127/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-128/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-129/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-13/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-13/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-130/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-131/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-132/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-133/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-134/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-14/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-14/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-15/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-15/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-16/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-16/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-17/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-18/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-18/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-19/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-2/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-20/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-21/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-22/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-23/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-23/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-24/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-24/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-25/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-25/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-26/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-27/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-27/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-28/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-29/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-29/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-3/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-3/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-30/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-31/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-32/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-32/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-33/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-34/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-35/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-36/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-37/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-37/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-37/v3/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-38/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-38/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-39/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-4/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-40/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-41/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-41/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-42/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-43/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-44/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-45/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-46/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-47/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-48/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-49/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-5/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-5/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-50/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-51/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-52/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-53/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-54/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-54/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-55/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-55/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-56/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-56/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-57/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-57/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-58/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-58/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-59/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-6/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-60/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-61/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-61/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-62/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-62/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-63/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-64/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-64/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-65/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-65/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-66/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-66/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-67/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-67/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-68/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-68/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-69/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-7/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-70/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-71/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-72/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-73/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-74/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-75/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-75/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-76/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-76/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-77/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-77/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-78/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-79/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-8/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-80/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-81/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-82/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-83/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-84/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-84/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-85/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-86/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-87/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-87/v2/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-88/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-89/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-9/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-90/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-91/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-92/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-93/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-94/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-95/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-96/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-97/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-98/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-99/v1/xml</item>
  <item>https://wellcomeopenresearch.org/articles/4-99/v2/xml</item>
</list>

for $x in $list//*:item
let $txt := fetch:text($x/text())
let $name := replace(concat('wellcomeopenresearch','-',substring-before(substring-after($x,'/articles/'),'/xml'),'.xml'),'/','-')
let $file-path := concat('/Users/fredatherden/Documents/f1000-xml/',$name)

return 
if ($txt = '') then ()
else 
let $xml := fetch:xml($x/text())
return file:write($file-path,$xml)

